version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.10
    container_name: weaviate
    ports:
      - "8080:8080"     # HTTP
      - "50051:50051"   # gRPC
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      DEFAULT_VECTORIZER_MODULE: 'none'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

volumes:
  weaviate_data:

